export const GET_PROFILE = "GET_PROFILE";
export const SET_PROFILE = "SET_PROFILE";
export const ADD_BALANCE = "ADD_BALANCE";
export const GET_BALANCE = "BALANCE_PROFILE";
export const LOG_OUT = "LOG_OUT";
export const ADD_SLOTS_MACHINE_RECORD = "ADD_SLOTS_MACHINE_RECORD";
